# A pipeline with no CI trigger
trigger: none

pr:
  branches:
    include:
    - master
    - releases/*
  paths:
    include:
    - Microsoft.Azure.Cosmos/*
    - NuGet.config

variables:
  DebugArguments: ' --filter "TestCategory!=Quarantine & TestCategory!=Functional & TestCategory=Preview" --verbosity normal '
  ReleaseArguments: ' --filter "TestCategory!=Quarantine & TestCategory!=Functional & TestCategory=Preview" --verbosity normal '
  VmImage: windows-latest # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
  Preview: 1


jobs:
- template:  templates/static-tools.yml
  parameters:
    BuildConfiguration: Release
    VmImage: $(VmImage)
        

#- template:  templates/build-test.yml
#  parameters:
#    BuildConfiguration: Debug
#    Arguments: $(DebugArguments)
#    VmImage: $(VmImage)

- template:  templates/build-test.yml
  parameters:
    BuildConfiguration: Release
    Arguments: $(ReleaseArguments)
    VmImage: $(VmImage)
  