# A pipeline with no CI trigger
trigger: none

pr: none

variables:
  DebugArguments: ' --filter "TestCategory!=Quarantine & TestCategory!=Functional" --verbosity normal '
  ReleaseArguments: ' --filter "TestCategory!=Quarantine & TestCategory!=Functional" --verbosity normal '
  VmImage: vs2017-win2016 # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
  Traces: 1


jobs:

#- template:  templates/build-test.yml
#  parameters:
#    BuildConfiguration: Debug
#    Arguments: $(DebugArguments)
#    VmImage: $(VmImage)

- template:  templates/build-test.yml
  parameters:
    BuildConfiguration: Release
    Arguments: $(ReleaseArguments)
    VmImage: $(VmImage)
  